name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.1.4
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
          tools: php-cs-fixer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest

      - name: Execute Tests
        run: |
          vendor/bin/phpunit --verbose
